"""Decision journal schema (v1).

Per the K2B architect greenlight 2026-04-18 on Bundle 1 m2.7. Version
stays at 1; bump to 2 only when promoting a metadata key to a top-level
field, and document the migration in
K2Bi-Vault/wiki/reference/journal-schema.md. Old records stay at v1;
readers must handle both. No history rewrites.

Required fields per record:
    ts                ISO-8601 UTC with microsecond precision
    schema_version    int -- currently 1
    event_type        enum (see EVENT_TYPES)
    trade_id          ULID or None -- lifecycle correlation across records
                      tied to one trade attempt
    journal_entry_id  ULID -- unique per record, generated by writer
    strategy          slug or None
    git_sha           short K2Bi repo SHA at decision time (None if absent)
    payload           object -- event-specific data

Optional fields:
    error     object {code, message, traceback_excerpt} for failure events
    metadata  object -- extension dict; promote 3+-recurring keys to
              top-level in next schema_version bump
    ticker    convenience top-level for grep (also can live in payload)
    side      convenience top-level (buy/sell)
    qty       convenience top-level

Event-type enum mirrors execution/journal/__init__.py + the two
additions from architect review (kill_switch_cleared already in original
enum; recovery_truncated is new).
"""

from __future__ import annotations

from typing import Any


SCHEMA_VERSION = 1

EVENT_TYPES = frozenset(
    {
        "validator_pass",
        "validator_reject",
        "order_submitted",
        "order_filled",
        "breaker_triggered",
        "kill_switch_written",
        "kill_switch_cleared",
        "recovery_truncated",
    }
)

REQUIRED_TOP_LEVEL = (
    "ts",
    "schema_version",
    "event_type",
    "trade_id",
    "journal_entry_id",
    "strategy",
    "git_sha",
    "payload",
)


class JournalSchemaError(ValueError):
    pass


def validate(record: dict[str, Any]) -> None:
    """Raise JournalSchemaError if the record can't be journaled.

    Cheap checks only: required-field presence, event_type enum, and
    schema_version == 1. Field-level payload shape is the caller's
    responsibility.
    """
    missing = [k for k in REQUIRED_TOP_LEVEL if k not in record]
    if missing:
        raise JournalSchemaError(f"missing required fields: {missing}")
    if record["event_type"] not in EVENT_TYPES:
        raise JournalSchemaError(f"unknown event_type: {record['event_type']}")
    if record["schema_version"] != SCHEMA_VERSION:
        raise JournalSchemaError(
            f"writer produces schema_version={SCHEMA_VERSION}, got {record['schema_version']}"
        )
